config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  get    'login',   to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users
  resources :events do
    member do
      post :attending
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :event_attendings, foreign_key: :attended_event_id, dependent: :delete_all
  has_many :attendees, through: :event_attendings, source: :attendee, dependent: :delete_all

  scope :upcoming, -> { where('event_date >= ?', Date.current) }
  scope :past, -> { where('event_date < ?', Date.current) }
end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  has_many :created_events, dependent: :destroy, foreign_key: "creator_id", class_name: "Event", dependent: :delete_all
  has_many :event_attendings, foreign_key: :attendee_id, dependent: :delete_all
  has_many :attended_events, through: :event_attendings, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_user
  protected
  def set_user
    @current_user = User.find_by(id: session[:id])
  end

  def authenticate_user
    redirect_to root_path, notice: "You're not authenticted user" if @current_user.blank?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

before_action :authenticate_user, only: [:new, :create]
  def new
    @created_event = Event.new
  end

  def create
    @created_event = @current_user.created_events.build(event_params)
    @created_event.save
    redirect_to @current_user
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
    @current_user_attending = @current_user.present? && @attendees.exists?(@current_user.id)
  end

  def index
    @events = Event.all
    @upcoming_events = @events.upcoming
    @past_events = @events.past
  end

  def event_params
    params.require(:event).permit(:description, :event_date)
  end

  def attending
  @current_user.event_attendings.create(attended_event_id: params[:event_id])
  redirect_to events_path   
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user= User.find_by(name: params[:session][:name])
    if @user
      #logs in the given user
      session[:id] = @user.id
      redirect_to @user
    else
      flash.now.notice = 'Invalid user name! Try Again.'
      render 'new'
    end
  end

  def destroy
    #logs out the current user
    session[:id] = nil
    @current_user = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #logs in the given user
    session[:id] = @user.id
    redirect_to @user
    end
  end

  def show
    @user = User.find(params[:id])
    @created_events=@user.created_events
    @upcoming_events = @user.attended_events.upcoming
    @past_events = @user.attended_events.past
  end

  def user_params
    params.require(:user).permit(:name)
  end

end
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>

<% if @upcoming_events.any? %>
  <h2>Upcoming Events</h2>
  <ul>
  <% @upcoming_events.each do |event| %>
    <li><h3><%= link_to event.description, event %></h3></li>
    <p><%= event.event_date %></p>
    <br>
  <% end %>
  </ul>
<% end %>

<% if @past_events.any? %>
  <h2>Past Events</h2>
  <ul>
  <% @past_events.each do |event| %>
    <li><h3><%= link_to event.description, event %></h3></li>
    <p><%= event.event_date %></p>
    <br>
  <% end %>
  </ul>
<% end %>

app/views/events/new.html.erb
<h1>Create Event</h1>

<%= form_for [@created_event] do |f| %>
  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.label :event_date %>
    <%= f.date_field :event_date %>
  </p>

  <p>
    <%= f.submit 'Create' %>
  </p>

<% end %>

app/views/events/show.html.erb
<p><h2>Hosted by: <%= @event.creator.name %></h2></p> 

<% if @current_user_attending %>
  <h4>Your Status: Attendee</h4>
<% elsif @current_user.present? %>
  <%= button_to 'Attend', attending_event_path(event_id: @event.id) %>
<% end %>

<h3>List of attendees</h3>

  <p>
  <% if @attendees.any? %>
    <ul>
    <% @attendees.each do |attendee| %>
    <li><%= attendee.name %></li>
    <% end %>
    </ul>
  <% end %>
  </p>

app/views/layouts/_navigate.html.erb
<nav>
  <ul class="nav navbar-nav navbar-right">
    <% if @current_user.present? %>
      <li><%= link_to "Profile",   '@current_user' %></li>
      <li><%= link_to "Logout", logout_path, method: :delete %></li>
    <% end %>

    <li><%= link_to "Events", events_path %></li>
    <li><%= link_to "Events", users_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
  <ul class="nav navbar-nav navbar-right">
    <% if @current_user.present? %>
      <li><%= link_to "Profile", @current_user %></li>
      <li><%= link_to "Create a New Event", new_event_path %></li>
      <li><%= link_to "Logout", logout_path, method: :delete %></li>
    <% end %>

    <li><%= link_to "Events", events_path %></li>
    <li><%= link_to "Users", users_path %></li>
  </ul>
</nav>
    <p><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>List of Users</h1>

<ul>
<% @users.each do |user| %>
  <li><%= user.name %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>
  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>

  <p>
    <%= f.label :name, "User Name" %>
    <br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>

  <% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h2>My Events</h2>

<% if @created_events.any? %>
  <% @created_events.each do |event| %>
  <h3><u><%= event.description %></u></h3>
  <p><%= event.event_date %></p>
  <br>
 <% end %>
<% end %>

<% if @upcoming_events.any? %>
  <h2>Upcoming Events</h2>
  <% @upcoming_events.each do |event| %>
   <h3><u><%= event.description %></u></h3>
   <p><%= event.event_date %></p>
   <br>
  <% end %>
<% end %>

<% if @past_events.any? %>
  <h2>Previously Attended Events</h2>
  <% @past_events.each do |event| %>
   <h3><u><%= event.description %></u></h3>
   <p><%= event.event_date %></p>
   <br>
  <% end %>
<% end %>